brew "awscli"
brew "bat"
brew "cheat"
brew "curl"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "helm"
brew "helmfile"
brew "htop"
brew "jq"
brew "k9s"
brew "krew"
brew "kubernetes-cli"
brew "kubie"
brew "lsd"
brew "nvm"
brew "python@3.13"
brew "pyenv"
brew "pipx"
brew "uv"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "stow"
brew "tfenv"
brew "tmux"
brew "spaceship"
brew "tree"
brew "watch"
brew "wget"
brew "xh"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "z"
cask "font-hack-nerd-font"

brew "pinentry-mac" if OS.mac?
cask "1password" if OS.mac?
cask "docker" if OS.mac?
cask "iterm2" if OS.mac?
cask "gpg-suite-no-mail" if OS.mac?
cask "slack" if OS.mac?
cask "visual-studio-code" if OS.mac?
cask "zoom" if OS.mac?
